version: "3.8"

volumes:
  node_vol: {}

services:
  nodejs:
    image: node:14
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "10000:8080"
    networks:
      - nodejs
      - mongo
  # ======================================================
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    networks:
      - mongo
  #======================================================
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
  #   networks:
  #     - mongo

  #======================================================
networks:
  nodejs:
  mongo:
