version: "3.8"

volumes:
  node_vol: {}

services:
  nodejs:
    image: node:14
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/usr/src/app/node/
      - /usr/src/app/node_modules
    ports:
      - "10000:8080"
    networks:
      - nodejs

networks:
  nodejs:
